### ISSUE TITLE
Location error

### ISSUE THREAD

**Issue by pruksmhc** [ebhy/budgetml#11]
**Describe the bug**
As a newbie in GCP, I'm trying to run BudgetML with the "getting started" code shared. After setting up GCP, and running run_budget_ml.py (which contains the budget_ml.launch() call), I get the following error:

Traceback (most recent call last):
  File "run_budget_ml.py", line 24, in <module>
    budgetml.launch(
  File "/Users/yadapruksachatkun/opt/anaconda3/lib/python3.8/site-packages/budgetml/main.py", line 321, in launch
    self.create_scheduler_job(
  File "/Users/yadapruksachatkun/opt/anaconda3/lib/python3.8/site-packages/budgetml/main.py", line 266, in create_scheduler_job
    create_gcp_scheduler_job(project_id, topic, schedule, region)
  File "/Users/yadapruksachatkun/opt/anaconda3/lib/python3.8/site-packages/budgetml/gcp/scheduler.py", line 30, in create_scheduler_job
    response = client.create_job(
  File "/Users/yadapruksachatkun/opt/anaconda3/lib/python3.8/site-packages/google/cloud/scheduler_v1/services/cloud_scheduler/client.py", line 595, in create_job
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/Users/yadapruksachatkun/opt/anaconda3/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/yadapruksachatkun/opt/anaconda3/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 75, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 Location must equal us-west2 because the App Engine app that is associated with this project is located in us-west2

My app engine region is us-west-2, and I also set my project region to us-west-2. What region should I be setting? 
Thank you!

**Comment by htahir1** [comment]
It might be due to some defaults picked up by the GCP SDK. Not sure how to fix yet, will investigate. In the meanwhile, can you try setting it
